modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="sao_legacy"
version="1.0.0"
displayName="The SAO Legacy Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="http://swordartlegacy.com"
authors="Cardinal"
description='''
Created for the SAO Legacy server
'''

[[dependencies.sao_legacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



